[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['/vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo      = 'tyru/caw.vim'

[[plugins]]
repo      = 't9md/vim-quickhl'

[[plugins]]
repo      = 'mattn/vim-lexiv'

[[plugins]]
repo      = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'junegunn/fzf'
build_on = '''
./install -all
'''

[[plugins]]
repo = 'junegunn/fzf.vim'

