[[plugins]]
repo = "tpope/vim-fugitive"

[[plugins]]
repo  = 'kannokanno/previm'
on_ft = ['markdown']

[[plugins]]
repo = 'Shougo/neocomplete.vim'
insert = 1

[[plugins]]
repo = 'vim-ruby/vim-ruby'

[[plugins]]
repo = 'vim-scripts/ruby-matchit'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'romanvbabenko/rails.vim'
